{
 "title": "Trades",
 "description": "https://clickhouse.com/blog/working-with-time-series-data-and-functions-ClickHouse",
 "time": { "from": "2024-12-06T06:57:21.009Z", "to": "2024-12-06T16:00:11.355Z" },
 "templating": {
  "list": [
   {
    "name": "sec_code",
    "label": "Инструмент",
    "query": "SELECT sec_code FROM \"default\".\"transaq_trades\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP by sec_code ORDER BY sec_code ASC LIMIT 1000"
   },
   {
    "name": "interval",
    "label": "Интервал агрегации в минутах",
    "query": "1,3,5,10,12,15,20,24,30,48,60,120,240,480"
   },
   {
    "name": "sec_code_etf",
    "label": "ETF",
    "query": "select sec_code from transaq_trades\njoin default.transaq_securities t on transaq_trades.secid = t.secid\nwhere board = 'TQTF' AND  time >= $__fromTime AND time <= $__toTime GROUP BY sec_code"
   }
  ]
 },
 "panels": [
  { "title": "Итоги дня", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Нетто покупки в IMOEX",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "select sec_code, sum(vol) as vol FROM (\n SELECT sec_code, sum(price * quantity * s.lotsize) as vol\n FROM \"default\".\"transaq_trades\"\n          JOIN default.transaq_securities s\n               on (transaq_trades.secid = s.secid and transaq_trades.board = s.board)\n WHERE sec_code not in [$sec_code_etf]\n   AND board = 'TQBR'\n   AND (time >= $__fromTime AND time <= $__toTime)\n   AND (buy_sell = 'B')\n GROUP By sec_code    \n UNION ALL\n SELECT sec_code, sum(price * quantity * s.lotsize)*-1 as vol\n FROM \"default\".\"transaq_trades\"\n          JOIN default.transaq_securities s\n               on (transaq_trades.secid = s.secid and transaq_trades.board = s.board)\n WHERE sec_code not in [$sec_code_etf] AND board = 'TQBR'\n   AND (time >= $__fromTime AND time <= $__toTime)\n   AND (buy_sell = 'S')\n GROUP By sec_code  \n ) GROUP by sec_code ORDER by vol desc LIMIT 10\n"
    }
   ]
  },
  {
   "title": "Нетто продажи в IMOEX",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "select sec_code, sum(vol)*-1 as vol FROM (\n  SELECT sec_code, sum(price * quantity * s.lotsize) as vol\n  FROM \"default\".\"transaq_trades\" JOIN default.transaq_securities s on (transaq_trades.secid = s.secid and transaq_trades.board = s.board)\n  WHERE sec_code not in [$sec_code_etf]\n    AND board = 'TQBR'\n    AND (time >= $__fromTime AND time <= $__toTime)\n    AND (buy_sell = 'B')\n  GROUP By sec_code \n  UNION ALL\n  SELECT sec_code, sum(price * quantity * s.lotsize)*-1 as vol\n  FROM \"default\".\"transaq_trades\" JOIN default.transaq_securities s on (transaq_trades.secid = s.secid and transaq_trades.board = s.board)\n  WHERE sec_code not in [$sec_code_etf] AND board = 'TQBR'\n    AND (time >= $__fromTime AND time <= $__toTime)\n    AND (buy_sell = 'S')\n  GROUP By sec_code  \n ) GROUP by sec_code ORDER by vol desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Volume anomalies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Айсберги",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT time, topK(10)(sec_code) as \"sec\", sum(quantity) as \"vol\"\nFROM \"default\".\"transaq_trades\"\nWHERE quantity = 1 AND buy_sell = 'B' AND ( time >= $__fromTime AND time <= $__toTime )\nGROUP by time, sec_code\nHAVING vol > 1\nORDER BY time"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume by sec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume trades $sec_code by interval $interval в минутах",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
     "targets": [
      {
       "rawSql": "SELECT minute , sum(vol) as \"разница объемов\" FROM (\n  SELECT toStartOfInterval(time, INTERVAL ${interval} MINUTE) as \"minute\", if(buy_sell == 'S', -1, 1) * sum(price * quantity * s.lotsize) as \"vol\"\n  FROM \"default\".\"transaq_trades\" JOIN default.transaq_securities s on (transaq_trades.sec_code = s.seccode and transaq_trades.board = s.board)\n  WHERE sec_code in [$sec_code] AND board = 'TQBR' AND ( minute >= $__fromTime AND minute <= $__toTime )\n  GROUP by \"minute\", buy_sell)\nGROUP by \"minute\"\nORDER BY minute"
      },
      {
       "rawSql": "SELECT minute , sum(vol) as \"разница объемов\" FROM (\n  SELECT toStartOfInterval(timestamp_add(day, 1, time), INTERVAL ${interval} MINUTE) as \"minute\", if(buy_sell == 'S', -1, 1) * sum(price * quantity * s.lotsize) as \"vol\"\n  FROM \"default\".\"transaq_trades\" JOIN default.transaq_securities s on (transaq_trades.sec_code = s.seccode and transaq_trades.board = s.board)\n  WHERE sec_code in [$sec_code] AND board = 'TQBR' AND ( minute >= $__fromTime AND minute <= $__toTime )\n  GROUP by \"minute\", buy_sell)\nGROUP by \"minute\"\nORDER BY minute"
      }
     ]
    },
    {
     "title": "Volume trades $sec_code by interval $interval в минутах",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfInterval(time, INTERVAL $interval MINUTE) as \"minute\", sum(price * quantity * s.lotsize) as \"объем\" FROM \"default\".\"transaq_trades\" \nJOIN default.transaq_securities s on (transaq_trades.secid = s.secid and transaq_trades.board = s.board)\nWHERE sec_code in [$sec_code] AND board = 'TQBR' AND ( minute >= $__fromTime AND minute <= $__toTime ) AND ( buy_sell = 'B' ) GROUP by \"minute\" ORDER BY minute"
      },
      {
       "rawSql": "SELECT toStartOfInterval(time, INTERVAL $interval MINUTE) as \"minute\", sum(price * quantity * s.lotsize) * -1 as \"объем\" \nFROM \"default\".\"transaq_trades\"\nJOIN default.transaq_securities s on (transaq_trades.secid = s.secid and transaq_trades.board = s.board)\nWHERE sec_code in [$sec_code] AND board = 'TQBR' AND ( minute >= $__fromTime AND minute <= $__toTime ) AND ( buy_sell = 'S' ) GROUP by minute ORDER BY minute"
      }
     ]
    },
    {
     "title": "Volume trades $sec_code в лотах",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT time, sum(quantity) as \"лот\" FROM \"default\".\"transaq_trades\" WHERE sec_code in [$sec_code] AND ( time >= $__fromTime AND time <= $__toTime ) AND ( buy_sell = 'B' ) GROUP BY time ORDER BY time ASC"
      },
      {
       "rawSql": "SELECT time, sum(quantity)*-1 as \"лот\" FROM \"default\".\"transaq_trades\" WHERE sec_code in [$sec_code] AND ( time >= $__fromTime AND time <= $__toTime ) AND ( buy_sell = 'S' ) GROUP BY time ORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Count trades $sec_code",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT time, count(price) as \"count\" FROM \"default\".\"transaq_trades\" WHERE sec_code in [$sec_code] AND ( time >= $__fromTime AND time <= $__toTime ) AND ( buy_sell = 'B' ) GROUP by time ORDER BY time ASC"
      },
      {
       "rawSql": "SELECT time, count(price)* -1 as \"count\" FROM \"default\".\"transaq_trades\" WHERE sec_code in [$sec_code] AND ( time >= $__fromTime AND time <= $__toTime ) AND ( buy_sell = 'S' ) GROUP by time ORDER BY time ASC"
      }
     ]
    }
   ]
  },
  { "title": "Volume Indexes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Volume trades IMOEX diff with buy ad sell by interval $interval в минутах",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "SELECT minute , sum(vol) as \"разница объемов\" FROM (\n  SELECT toStartOfInterval(time, INTERVAL ${interval} MINUTE) as \"minute\", if(buy_sell == 'S', -1, 1) * sum(price * quantity * s.lotsize) as \"vol\"\n  FROM \"default\".\"transaq_trades\" JOIN default.transaq_securities s on (transaq_trades.sec_code = s.seccode and transaq_trades.board = s.board)\n  WHERE sec_code not in [$sec_code_etf] AND board = 'TQBR' AND ( minute >= $__fromTime AND minute <= $__toTime )\n  GROUP by \"minute\", buy_sell)\nGROUP by \"minute\"\nORDER BY minute"
    },
    {
     "rawSql": "SELECT minute , sum(vol) as \"разница объемов\" FROM (\n  SELECT toStartOfInterval(timestamp_add(day, 1, time), INTERVAL ${interval} MINUTE) as \"minute\", if(buy_sell == 'S', -1, 1) * sum(price * quantity * s.lotsize) as \"vol\"\n  FROM \"default\".\"transaq_trades\" JOIN default.transaq_securities s on (transaq_trades.sec_code = s.seccode and transaq_trades.board = s.board)\n  WHERE sec_code not in [$sec_code_etf] AND board = 'TQBR' AND ( minute >= $__fromTime AND minute <= $__toTime )\n  GROUP by \"minute\", buy_sell)\nGROUP by \"minute\"\nORDER BY minute"
    }
   ]
  },
  {
   "title": "Volume trades IMOEX by interval $interval в минутах",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(time, INTERVAL $interval MINUTE) as \"minute\", sum(price * quantity) as \"объем\" FROM \"default\".\"transaq_trades\" WHERE ( minute >= $__fromTime AND minute <= $__toTime ) AND ( buy_sell = 'B' ) AND sec_code not in [$sec_code_etf] AND board = 'TQBR' GROUP by \"minute\" ORDER BY minute ASC LIMIT 10000"
    },
    {
     "rawSql": "SELECT toStartOfInterval(time, INTERVAL $interval MINUTE) as \"minute\", sum(price * quantity)*-1 as \"объем\" FROM \"default\".\"transaq_trades\" WHERE ( minute >= $__fromTime AND minute <= $__toTime ) AND ( buy_sell = 'S' ) AND sec_code not in [$sec_code_etf] AND board = 'TQBR' GROUP by minute ORDER BY minute ASC LIMIT 10000"
    }
   ]
  },
  {
   "title": "Volume trades ETF by interval $interval в минутах",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(time, INTERVAL $interval MINUTE) as \"minute\", sum(price * quantity) as \"объем\" FROM \"default\".\"transaq_trades\" WHERE ( minute >= $__fromTime AND minute <= $__toTime ) AND ( buy_sell = 'B' ) AND sec_code in [$sec_code_etf] GROUP by \"minute\" ORDER BY minute ASC LIMIT 10000"
    },
    {
     "rawSql": "SELECT toStartOfInterval(time, INTERVAL $interval MINUTE) as \"minute\", sum(price * quantity)*-1 as \"объем\" FROM \"default\".\"transaq_trades\" WHERE  sec_code in [$sec_code_etf] AND ( minute >= $__fromTime AND minute <= $__toTime ) AND ( buy_sell = 'S' ) GROUP by minute ORDER BY minute ASC LIMIT 10000"
    }
   ]
  },
  {
   "title": "Volume trades IMOEX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "SELECT time, sum(price * quantity) as \"vol\" FROM \"default\".\"transaq_trades\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( buy_sell = 'B' ) AND sec_code not in [$sec_code_etf] GROUP BY time ORDER BY time ASC"
    },
    {
     "rawSql": "SELECT time, sum(price * quantity)*-1 as \"vol\" FROM \"default\".\"transaq_trades\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( buy_sell = 'S' ) AND sec_code not in [$sec_code_etf] GROUP BY time  ORDER BY time ASC"
    }
   ]
  }
 ]
}